version: "3"
services:
  app:
    container_name: go_app
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - go-postgres
    networks:
      - backend
  go-postgres:
    image: postgres:latest
    container_name: db_postgres
    environment:
      - POSTGRES_USER=amrmohamed
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=users
      - DATABASE_HOST=5432
    ports:
      - 5432:5432
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - backend
  client:
    container_name: react_app
    build:
      context: ./frontend/react_app
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    restart: on-failure
    volumes:
      - ./frontend/react_app/src:/app/src
      - /app/node_modules
    depends_on:
      - app

volumes:
  api:
  database_postgres:

# Networks to be created to facilitate communication between containers
networks:
  backend:
    driver: bridge
